fix: 修复以下错误 ‘’‘ Loading ETH&UCY data from /Users/sunknight/workspace/codes/eth_dataset/ETH/ETH.txt 2025-06-10 11:05:16.382 Examining the path of torch.classes raised: Traceback (most recent call last):   File "/Users/sunknight/miniconda3/envs/ped_pred/lib/python3.10/site-packages/streamlit/web/bootstrap.py", line 347, in run     if asyncio.get_running_loop().is_running(): RuntimeError: no running event loop
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sunknight/miniconda3/envs/ped_pred/lib/python3.10/site-packages/streamlit/watcher/local_sources_watcher.py", line 217, in get_module_paths
    potential_paths = extract_paths(module)
  File "/Users/sunknight/miniconda3/envs/ped_pred/lib/python3.10/site-packages/streamlit/watcher/local_sources_watcher.py", line 210, in <lambda>
    lambda m: list(m.__path__._path),
  File "/Users/sunknight/miniconda3/envs/ped_pred/lib/python3.10/site-packages/torch/_classes.py", line 13, in __getattr__
    proxy = torch._C._get_custom_class_python_wrapper(self.name, attr)
RuntimeError: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_
’‘’